var o = getApp();

Page({
    data: {
        indicatorDots: !1,
        autoplay: !0,
        interval: 4e3,
        duration: 1e3,
        imgUrls: [ "../image/haibao/3.jpg", "../image/haibao/hs300.jpg", "../image/haibao/s100.jpg" ],
        imgArr: [ "https://mmbiz.qpic.cn/mmbiz_jpg/PY3esKicffFGYMv3icAIh1gMUnAlF6RGQzN82xHeGmjgtCUYlicN69luE4k7nibbtarDID9DAOFrS0KOjPqskjxYZw/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1", "https://mmbiz.qpic.cn/mmbiz_jpg/PY3esKicffFGYMv3icAIh1gMUnAlF6RGQzeCVPTiaiaNhwZHMsgvD6to17SHVgUJZNfZrDcAH1waewzEriaoG8G3k6w/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1" ],
        stock_fund: [ {
            stockcode: "601318",
            stockname: "中国平安"
        }, {
            stockcode: "0700",
            stockname: "腾讯控股有限公司"
        }, {
            stockcode: "BABA",
            stockname: "阿里巴巴"
        }, {
            stockcode: "600276",
            stockname: "恒瑞医药"
        }, {
            stockcode: "MSFT",
            stockname: "微软公司"
        }, {
            stockcode: "AAPL",
            stockname: "苹果公司"
        }, {
            stockcode: "600030",
            stockname: "中信证券"
        }, {
            stockcode: "600036",
            stockname: "招商银行"
        }, {
            stockcode: "601166",
            stockname: "兴业银行"
        }, {
            stockcode: "0939",
            stockname: "建设银行"
        }, {
            stockcode: "000661",
            stockname: "长春高新"
        }, {
            stockcode: "0700",
            stockname: "腾讯控股"
        }, {
            stockcode: "600519",
            stockname: "贵州茅台"
        }, {
            stockcode: "603707",
            stockname: "健友股份"
        }, {
            stockcode: "BABA",
            stockname: "阿里巴巴集团控股有限公司"
        }, {
            stockcode: "600570",
            stockname: "恒生电子"
        }, {
            stockcode: "002013",
            stockname: "中航机电"
        }, {
            stockcode: "002007",
            stockname: "华兰生物"
        }, {
            stockcode: "000860",
            stockname: "顺鑫农业"
        }, {
            stockcode: "002410",
            stockname: "广联达"
        }, {
            stockcode: "000568",
            stockname: "泸州老窖"
        }, {
            stockcode: "000858",
            stockname: "五粮液"
        }, {
            stockcode: "JD",
            stockname: "京东"
        }, {
            stockcode: "002415",
            stockname: "海康威视"
        }, {
            stockcode: "600809",
            stockname: "山西汾酒"
        }, {
            stockcode: "002179",
            stockname: "中航光电"
        }, {
            stockcode: "0388",
            stockname: "香港交易所"
        }, {
            stockcode: "TCOM",
            stockname: "携程国际有限公司"
        }, {
            stockcode: "600887",
            stockname: "伊利股份"
        }, {
            stockcode: "600967",
            stockname: "内蒙一机"
        }, {
            stockcode: "000651",
            stockname: "格力电器"
        }, {
            stockcode: "300253",
            stockname: "卫宁健康"
        }, {
            stockcode: "600066",
            stockname: "宇通客车"
        }, {
            stockcode: "1177",
            stockname: "中国生物制药有限公司"
        }, {
            stockcode: "1093",
            stockname: "石药集团"
        }, {
            stockcode: "002153",
            stockname: "石基信息"
        }, {
            stockcode: "600009",
            stockname: "上海机场"
        }, {
            stockcode: "MC",
            stockname: "LVMHORD"
        }, {
            stockcode: "002025",
            stockname: "航天电器"
        }, {
            stockcode: "1177",
            stockname: "中国生物制药"
        }, {
            stockcode: "3690",
            stockname: "美团点评-W"
        }, {
            stockcode: "300628",
            stockname: "亿联网络"
        }, {
            stockcode: "601658",
            stockname: "邮储银行"
        }, {
            stockcode: "TAL",
            stockname: "好未来教育集团"
        }, {
            stockcode: "AMZN",
            stockname: "亚马逊公司"
        }, {
            stockcode: "2318",
            stockname: "中国平安"
        }, {
            stockcode: "TSLA",
            stockname: "特斯拉"
        }, {
            stockcode: "000333",
            stockname: "美的集团"
        }, {
            stockcode: "000878",
            stockname: "云南铜业"
        }, {
            stockcode: "600486",
            stockname: "扬农化工"
        }, {
            stockcode: "000596",
            stockname: "古井贡酒"
        }, {
            stockcode: "600837",
            stockname: "海通证券"
        }, {
            stockcode: "300476",
            stockname: "胜宏科技"
        }, {
            stockcode: "2269",
            stockname: "药明生物"
        }, {
            stockcode: "601012",
            stockname: "隆基股份"
        }, {
            stockcode: "300498",
            stockname: "温氏股份"
        }, {
            stockcode: "603259",
            stockname: "药明康德"
        }, {
            stockcode: "EDU",
            stockname: "新东方"
        }, {
            stockcode: "600547",
            stockname: "山东黄金"
        }, {
            stockcode: "601989",
            stockname: "中国重工"
        }, {
            stockcode: "603806",
            stockname: "福斯特"
        }, {
            stockcode: "600588",
            stockname: "用友网络"
        }, {
            stockcode: "1398",
            stockname: "工商银行"
        }, {
            stockcode: "002050",
            stockname: "三花智控"
        }, {
            stockcode: "300142",
            stockname: "沃森生物"
        }, {
            stockcode: "600690",
            stockname: "海尔智家"
        }, {
            stockcode: "601899",
            stockname: "紫金矿业"
        }, {
            stockcode: "600048",
            stockname: "保利地产"
        }, {
            stockcode: "KER",
            stockname: "Kering"
        }, {
            stockcode: "300601",
            stockname: "康泰生物"
        }, {
            stockcode: "600161",
            stockname: "天坛生物"
        }, {
            stockcode: "603688",
            stockname: "石英股份"
        }, {
            stockcode: "000733",
            stockname: "振华科技"
        }, {
            stockcode: "300059",
            stockname: "东方财富"
        }, {
            stockcode: "002850",
            stockname: "科达利"
        }, {
            stockcode: "000002",
            stockname: "万科A"
        }, {
            stockcode: "002127",
            stockname: "南极电商"
        }, {
            stockcode: "600031",
            stockname: "三一重工"
        }, {
            stockcode: "0941",
            stockname: "中国移动"
        }, {
            stockcode: "601328",
            stockname: "交通银行"
        }, {
            stockcode: "600016",
            stockname: "民生银行"
        }, {
            stockcode: "300015",
            stockname: "爱尔眼科"
        }, {
            stockcode: "EL",
            stockname: "雅诗兰黛公司"
        }, {
            stockcode: "3690",
            stockname: "美团点评"
        }, {
            stockcode: "601137",
            stockname: "博威合金"
        }, {
            stockcode: "300347",
            stockname: "泰格医药"
        }, {
            stockcode: "300760",
            stockname: "迈瑞医疗"
        }, {
            stockcode: "NKE",
            stockname: "耐克公司"
        }, {
            stockcode: "000768",
            stockname: "中航飞机"
        }, {
            stockcode: "688029",
            stockname: "南微医学"
        }, {
            stockcode: "300122",
            stockname: "智飞生物"
        }, {
            stockcode: "300750",
            stockname: "宁德时代"
        }, {
            stockcode: "600845",
            stockname: "宝信软件"
        }, {
            stockcode: "601688",
            stockname: "华泰证券"
        }, {
            stockcode: "601288",
            stockname: "农业银行"
        }, {
            stockcode: "600004",
            stockname: "白云机场"
        }, {
            stockcode: "002311",
            stockname: "海大集团"
        }, {
            stockcode: "000001",
            stockname: "平安银行"
        }, {
            stockcode: "300413",
            stockname: "芒果超媒"
        }, {
            stockcode: "002465",
            stockname: "海格通信"
        }, {
            stockcode: "601211",
            stockname: "国泰君安"
        }, {
            stockcode: "003816",
            stockname: "中国广核"
        }, {
            stockcode: "601816",
            stockname: "京沪高铁"
        }, {
            stockcode: "300699",
            stockname: "光威复材"
        }, {
            stockcode: "2382",
            stockname: "舜宇光学科技"
        }, {
            stockcode: "600216",
            stockname: "浙江医药"
        }, {
            stockcode: "002734",
            stockname: "利民股份"
        }, {
            stockcode: "600000",
            stockname: "浦发银行"
        }, {
            stockcode: "600585",
            stockname: "海螺水泥"
        }, {
            stockcode: "603378",
            stockname: "亚士创能"
        }, {
            stockcode: "600893",
            stockname: "航发动力"
        }, {
            stockcode: "002182",
            stockname: "云海金属"
        }, {
            stockcode: "002032",
            stockname: "苏泊尔"
        }, {
            stockcode: "002236",
            stockname: "大华股份"
        }, {
            stockcode: "002475",
            stockname: "立讯精密"
        }, {
            stockcode: "601636",
            stockname: "旗滨集团"
        }, {
            stockcode: "0291",
            stockname: "华润啤酒"
        }, {
            stockcode: "601398",
            stockname: "工商银行"
        }, {
            stockcode: "002402",
            stockname: "和而泰"
        }, {
            stockcode: "601799",
            stockname: "星宇股份"
        }, {
            stockcode: "002304",
            stockname: "洋河股份"
        }, {
            stockcode: "300037",
            stockname: "新宙邦"
        }, {
            stockcode: "600019",
            stockname: "宝钢股份"
        }, {
            stockcode: "1951",
            stockname: "锦欣生殖"
        }, {
            stockcode: "603960",
            stockname: "克来机电"
        }, {
            stockcode: "600900",
            stockname: "长江电力"
        }, {
            stockcode: "300482",
            stockname: "万孚生物"
        }, {
            stockcode: "002597",
            stockname: "金禾实业"
        }, {
            stockcode: "300113",
            stockname: "顺网科技"
        }, {
            stockcode: "600118",
            stockname: "中国卫星"
        }, {
            stockcode: "002396",
            stockname: "星网锐捷"
        }, {
            stockcode: "300792",
            stockname: "壹网壹创"
        }, {
            stockcode: "1579",
            stockname: "颐海国际"
        }, {
            stockcode: "601877",
            stockname: "正泰电器"
        }, {
            stockcode: "601668",
            stockname: "中国建筑"
        }, {
            stockcode: "603993",
            stockname: "洛阳钼业"
        }, {
            stockcode: "BIDU",
            stockname: "百度股份有限公司"
        }, {
            stockcode: "300433",
            stockname: "蓝思科技"
        }, {
            stockcode: "DGE",
            stockname: "SHISEIDO"
        }, {
            stockcode: "002258",
            stockname: "利尔化学"
        }, {
            stockcode: "RMS",
            stockname: "爱马仕国际"
        }, {
            stockcode: "3988",
            stockname: "中国银行"
        }, {
            stockcode: "V",
            stockname: "VISA公司"
        }, {
            stockcode: "600739",
            stockname: "辽宁成大"
        }, {
            stockcode: "000807",
            stockname: "云铝股份"
        }, {
            stockcode: "6185",
            stockname: "康希诺生物股份公司"
        }, {
            stockcode: "000625",
            stockname: "长安汽车"
        }, {
            stockcode: "300770",
            stockname: "新媒股份"
        }, {
            stockcode: "002049",
            stockname: "紫光国微"
        }, {
            stockcode: "601601",
            stockname: "中国太保"
        }, {
            stockcode: "000902",
            stockname: "新洋丰"
        }, {
            stockcode: "4911",
            stockname: "0"
        }, {
            stockcode: "000547",
            stockname: "航天发展"
        }, {
            stockcode: "600760",
            stockname: "中航沈飞"
        }, {
            stockcode: "3888",
            stockname: "金山软件"
        }, {
            stockcode: "603883",
            stockname: "老百姓"
        }, {
            stockcode: "1299",
            stockname: "友邦保险"
        }, {
            stockcode: "002242",
            stockname: "九阳股份"
        }, {
            stockcode: "6098",
            stockname: "碧桂园服务"
        }, {
            stockcode: "601865",
            stockname: "福莱特"
        }, {
            stockcode: "000538",
            stockname: "云南白药"
        }, {
            stockcode: "002080",
            stockname: "中材科技"
        }, {
            stockcode: "600737",
            stockname: "中粮糖业"
        }, {
            stockcode: "300326",
            stockname: "凯利泰"
        }, {
            stockcode: "002142",
            stockname: "宁波银行"
        }, {
            stockcode: "603338",
            stockname: "浙江鼎力"
        }, {
            stockcode: "002001",
            stockname: "新和成"
        }, {
            stockcode: "603260",
            stockname: "合盛硅业"
        }, {
            stockcode: "002531",
            stockname: "天顺风能"
        }, {
            stockcode: "RI",
            stockname: "PERNODRICARDO"
        }, {
            stockcode: "600879",
            stockname: "航天电子"
        }, {
            stockcode: "0241",
            stockname: "阿里健康"
        }, {
            stockcode: "600999",
            stockname: "招商证券"
        }, {
            stockcode: "2269",
            stockname: "药明生物技术有限公司"
        }, {
            stockcode: "002690",
            stockname: "美亚光电"
        }, {
            stockcode: "002714",
            stockname: "牧原股份"
        }, {
            stockcode: "601916",
            stockname: "浙商银行"
        }, {
            stockcode: "1797",
            stockname: "新东方在线"
        }, {
            stockcode: "300496",
            stockname: "中科创达"
        }, {
            stockcode: "300119",
            stockname: "瑞普生物"
        }, {
            stockcode: "INTC",
            stockname: "英特尔公司"
        }, {
            stockcode: "000401",
            stockname: "冀东水泥"
        }, {
            stockcode: "002268",
            stockname: "卫士通"
        }, {
            stockcode: "0586",
            stockname: "海螺创业"
        }, {
            stockcode: "600038",
            stockname: "中直股份"
        }, {
            stockcode: "300502",
            stockname: "新易盛"
        }, {
            stockcode: "300207",
            stockname: "欣旺达"
        }, {
            stockcode: "002938",
            stockname: "鹏鼎控股"
        }, {
            stockcode: "2338",
            stockname: "潍柴动力"
        }, {
            stockcode: "300003",
            stockname: "乐普医疗"
        }, {
            stockcode: "FB",
            stockname: "FacebookInc"
        }, {
            stockcode: "1193",
            stockname: "华润燃气"
        }, {
            stockcode: "GOOG",
            stockname: "谷歌(Alphabet)"
        }, {
            stockcode: "601088",
            stockname: "中国神华"
        }, {
            stockcode: "GOOGL",
            stockname: "谷歌(Alphabet)"
        }, {
            stockcode: "600436",
            stockname: "片仔癀"
        }, {
            stockcode: "600183",
            stockname: "生益科技"
        }, {
            stockcode: "0268",
            stockname: "金蝶国际"
        }, {
            stockcode: "MA",
            stockname: "万事达卡公司"
        }, {
            stockcode: "002120",
            stockname: "韵达股份"
        }, {
            stockcode: "300144",
            stockname: "宋城演艺"
        }, {
            stockcode: "601988",
            stockname: "中国银行"
        }, {
            stockcode: "300661",
            stockname: "圣邦股份"
        }, {
            stockcode: "603288",
            stockname: "海天味业"
        }, {
            stockcode: "600763",
            stockname: "通策医疗"
        }, {
            stockcode: "000603",
            stockname: "盛达资源"
        }, {
            stockcode: "601169",
            stockname: "北京银行"
        }, {
            stockcode: "NTES",
            stockname: "网易公司"
        }, {
            stockcode: "000656",
            stockname: "金科股份"
        }, {
            stockcode: "002202",
            stockname: "金风科技"
        }, {
            stockcode: "6186",
            stockname: "中国飞鹤"
        }, {
            stockcode: "600309",
            stockname: "万华化学"
        }, {
            stockcode: "300394",
            stockname: "天孚通信"
        }, {
            stockcode: "601800",
            stockname: "中国交建"
        }, {
            stockcode: "002075",
            stockname: "沙钢股份"
        }, {
            stockcode: "000776",
            stockname: "广发证券"
        }, {
            stockcode: "000166",
            stockname: "申万宏源"
        }, {
            stockcode: "002624",
            stockname: "完美世界"
        }, {
            stockcode: "002056",
            stockname: "横店东磁"
        }, {
            stockcode: "002146",
            stockname: "荣盛发展"
        }, {
            stockcode: "603520",
            stockname: "司太立"
        }, {
            stockcode: "300078",
            stockname: "思创医惠"
        }, {
            stockcode: "0817",
            stockname: "中国金茂"
        }, {
            stockcode: "000975",
            stockname: "银泰黄金"
        }, {
            stockcode: "600867",
            stockname: "通化东宝"
        }, {
            stockcode: "600489",
            stockname: "中金黄金"
        }, {
            stockcode: "0883",
            stockname: "中国海洋石油"
        }, {
            stockcode: "600779",
            stockname: "水井坊"
        }, {
            stockcode: "300226",
            stockname: "上海钢联"
        }, {
            stockcode: "600380",
            stockname: "健康元"
        }, {
            stockcode: "603160",
            stockname: "汇顶科技"
        }, {
            stockcode: "CSCO",
            stockname: "思科"
        }, {
            stockcode: "601872",
            stockname: "招商轮船"
        }, {
            stockcode: "NVDA",
            stockname: "英伟达公司"
        }, {
            stockcode: "600958",
            stockname: "东方证券"
        }, {
            stockcode: "3968",
            stockname: "招商银行"
        }, {
            stockcode: "REGN",
            stockname: "再生元制药股份有限公司"
        }, {
            stockcode: "300676",
            stockname: "华大基因"
        }, {
            stockcode: "002777",
            stockname: "久远银海"
        }, {
            stockcode: "001914",
            stockname: "招商积余"
        }, {
            stockcode: "ADBE",
            stockname: "奥多比公司"
        }, {
            stockcode: "000063",
            stockname: "中兴通讯"
        }, {
            stockcode: "MRNA",
            stockname: "Moderna,Inc."
        }, {
            stockcode: "601077",
            stockname: "渝农商行"
        }, {
            stockcode: "600507",
            stockname: "方大特钢"
        }, {
            stockcode: "2359",
            stockname: "药明康德"
        }, {
            stockcode: "000423",
            stockname: "东阿阿胶"
        }, {
            stockcode: "002230",
            stockname: "科大讯飞"
        }, {
            stockcode: "3319",
            stockname: "雅生活服务"
        }, {
            stockcode: "601901",
            stockname: "方正证券"
        }, {
            stockcode: "600104",
            stockname: "上汽集团"
        }, {
            stockcode: "603416",
            stockname: "信捷电气"
        }, {
            stockcode: "603033",
            stockname: "三维股份"
        }, {
            stockcode: "GILD",
            stockname: "吉利德科学公司"
        }, {
            stockcode: "PDD",
            stockname: "拼多多"
        }, {
            stockcode: "603328",
            stockname: "依顿电子"
        }, {
            stockcode: "600346",
            stockname: "恒力石化"
        }, {
            stockcode: "002332",
            stockname: "仙琚制药"
        }, {
            stockcode: "601377",
            stockname: "兴业证券"
        }, {
            stockcode: "002594",
            stockname: "比亚迪"
        }, {
            stockcode: "000403",
            stockname: "双林生物"
        }, {
            stockcode: "VRTX",
            stockname: "福泰制药公司"
        }, {
            stockcode: "2628",
            stockname: "中国人寿"
        }, {
            stockcode: "002027",
            stockname: "分众传媒"
        }, {
            stockcode: "601628",
            stockname: "中国人寿"
        }, {
            stockcode: "BIIB",
            stockname: "生物基因公司"
        }, {
            stockcode: "601919",
            stockname: "中远海控"
        }, {
            stockcode: "UTHR",
            stockname: "UNITEDTHERAPEUTICSCORP"
        }, {
            stockcode: "BMRN",
            stockname: "拜玛林制药股份有限公司"
        }, {
            stockcode: "002367",
            stockname: "康力电梯"
        }, {
            stockcode: "CRM",
            stockname: "赛富时公司"
        }, {
            stockcode: "LLY",
            stockname: "礼来公司"
        }, {
            stockcode: "600933",
            stockname: "爱柯迪"
        }, {
            stockcode: "603916",
            stockname: "苏博特"
        }, {
            stockcode: "002110",
            stockname: "三钢闽光"
        }, {
            stockcode: "002601",
            stockname: "龙蟒佰利"
        }, {
            stockcode: "SGEN",
            stockname: "SEATTLEGENETICSINC/WA"
        }, {
            stockcode: "600028",
            stockname: "中国石化"
        }, {
            stockcode: "600873",
            stockname: "梅花生物"
        }, {
            stockcode: "0853",
            stockname: "微创医疗"
        }, {
            stockcode: "ABC",
            stockname: "美源伯根公司"
        }, {
            stockcode: "1109",
            stockname: "华润置地"
        }, {
            stockcode: "601229",
            stockname: "上海银行"
        }, {
            stockcode: "1093",
            stockname: "石药集团有限公司"
        }, {
            stockcode: "EXEL",
            stockname: "伊克力西斯公司"
        }, {
            stockcode: "600466",
            stockname: "蓝光发展"
        }, {
            stockcode: "002352",
            stockname: "顺丰控股"
        }, {
            stockcode: "ACAD",
            stockname: "阿卡迪亚公司"
        }, {
            stockcode: "002398",
            stockname: "垒知集团"
        }, {
            stockcode: "PEP",
            stockname: "百事公司"
        }, {
            stockcode: "NFLX",
            stockname: "奈飞公司"
        }, {
            stockcode: "002273",
            stockname: "水晶光电"
        }, {
            stockcode: "600919",
            stockname: "江苏银行"
        }, {
            stockcode: "PYPL",
            stockname: "PayPalHoldings,Inc."
        }, {
            stockcode: "002706",
            stockname: "良信电器"
        }, {
            stockcode: "DVA",
            stockname: "达维塔公司"
        }, {
            stockcode: "MCK",
            stockname: "麦克森公司"
        }, {
            stockcode: "002244",
            stockname: "滨江集团"
        }, {
            stockcode: "601319",
            stockname: "中国人保"
        }, {
            stockcode: "BAX",
            stockname: "百特国际有限公司"
        }, {
            stockcode: "CNC",
            stockname: "CenteneCorp"
        }, {
            stockcode: "600438",
            stockname: "通威股份"
        }, {
            stockcode: "1310",
            stockname: "香港宽频"
        }, {
            stockcode: "600741",
            stockname: "华域汽车"
        }, {
            stockcode: "2669",
            stockname: "中海物业"
        }, {
            stockcode: "0354",
            stockname: "中国软件国际"
        }, {
            stockcode: "603986",
            stockname: "兆易创新"
        }, {
            stockcode: "601003",
            stockname: "柳钢股份"
        }, {
            stockcode: "300115",
            stockname: "长盈精密"
        }, {
            stockcode: "BRK_B",
            stockname: "伯克希尔哈撒韦公司"
        }, {
            stockcode: "002233",
            stockname: "塔牌集团"
        }, {
            stockcode: "6049",
            stockname: "保利物业"
        }, {
            stockcode: "JNJ",
            stockname: "强生公司"
        }, {
            stockcode: "603179",
            stockname: "新泉股份"
        }, {
            stockcode: "600377",
            stockname: "宁沪高速"
        }, {
            stockcode: "1818",
            stockname: "招金矿业"
        }, {
            stockcode: "1789",
            stockname: "爱康医疗"
        }, {
            stockcode: "000977",
            stockname: "浪潮信息"
        }, {
            stockcode: "300573",
            stockname: "兴齐眼药"
        }, {
            stockcode: "601117",
            stockname: "中国化学"
        }, {
            stockcode: "JPM",
            stockname: "摩根大通"
        }, {
            stockcode: "601933",
            stockname: "永辉超市"
        }, {
            stockcode: "601939",
            stockname: "建设银行"
        }, {
            stockcode: "603939",
            stockname: "益丰药房"
        }, {
            stockcode: "002884",
            stockname: "凌霄泵业"
        }, {
            stockcode: "1801",
            stockname: "信达生物制药"
        }, {
            stockcode: "300657",
            stockname: "弘信电子"
        }, {
            stockcode: "603786",
            stockname: "科博达"
        }, {
            stockcode: "002250",
            stockname: "联化科技"
        }, {
            stockcode: "VIPS",
            stockname: "唯品会控股有限公司"
        }, {
            stockcode: "002375",
            stockname: "亚厦股份"
        }, {
            stockcode: "002376",
            stockname: "新北洋"
        }, {
            stockcode: "600703",
            stockname: "三安光电"
        }, {
            stockcode: "600745",
            stockname: "闻泰科技"
        }, {
            stockcode: "601336",
            stockname: "新华保险"
        }, {
            stockcode: "600383",
            stockname: "金地集团"
        }, {
            stockcode: "600704",
            stockname: "物产中大"
        }, {
            stockcode: "002371",
            stockname: "北方华创"
        }, {
            stockcode: "300014",
            stockname: "亿纬锂能"
        }, {
            stockcode: "002463",
            stockname: "沪电股份"
        }, {
            stockcode: "600886",
            stockname: "国投电力"
        }, {
            stockcode: "300383",
            stockname: "光环新网"
        }, {
            stockcode: "601111",
            stockname: "中国国航"
        }, {
            stockcode: "002385",
            stockname: "大北农"
        }, {
            stockcode: "600201",
            stockname: "生物股份"
        }, {
            stockcode: "603444",
            stockname: "吉比特"
        }, {
            stockcode: "002065",
            stockname: "东华软件"
        }, {
            stockcode: "002129",
            stockname: "中环股份"
        }, {
            stockcode: "688111",
            stockname: "金山办公"
        }, {
            stockcode: "000402",
            stockname: "金融街"
        }, {
            stockcode: "688278",
            stockname: "特宝生物"
        }, {
            stockcode: "603353",
            stockname: "和顺石油"
        }, {
            stockcode: "603983",
            stockname: "丸美股份"
        }, {
            stockcode: "603317",
            stockname: "天味食品"
        } ]
    },
    onLoad: function(o) {},
    onReady: function() {},
    onShow: function() {},
    onHide: function() {},
    onUnload: function() {},
    onPullDownRefresh: function() {},
    onReachBottom: function() {},
    onShareAppMessage: function(o) {
        return "button" === o.from && console.log(o.target), {
            title: "看净值·读季报·查基金",
            path: "/pages/fundvalue/fundvalue",
            imageUrl: "/pages/image/fengmian.jpg",
            success: function(o) {
                console.log("转发成功:");
            },
            fail: function(o) {
                console.log("转发失败:");
            }
        };
    },
    imgFund: function(o) {
        var c = o.currentTarget.dataset.index, t = this.data.imgArr;
        wx.previewImage({
            current: t[c],
            urls: t
        });
    },
    random: function() {
        var c = parseInt(this.data.stock_fund.length * Math.random());
        console.log("r:", c), o.globalData.code = this.data.stock_fund[c].stockcode, o.globalData.stockname = this.data.stock_fund[c].stockname, 
        wx.redirectTo({
            url: "../getfund/getfund"
        });
    },
    formSubmit: function(c) {
        for (var t = c.detail.value.id, e = 0, s = 0, k = 0; k < this.data.stock_fund.length; k++) t == this.data.stock_fund[k].stockcode ? (e = 1, 
        s = k) : this.data.stock_fund[k].stockname.match(RegExp(t)) && (e = 2, s = k);
        1 == e ? (console.log(t), o.globalData.code = this.data.stock_fund[s].stockcode, 
        o.globalData.stockname = this.data.stock_fund[s].stockname, wx.redirectTo({
            url: "../getfund/getfund"
        })) : 2 == e && t.length > 0 ? (console.log("formData：", t), o.globalData.code = 0, 
        o.globalData.stockname = t, wx.redirectTo({
            url: "../getfund/getfund"
        })) : (console.log("no this data"), console.log(t.length), 0 == t.length ? wx.showModal({
            title: "",
            content: "请先输入股票代码或股票名称再点击搜索！"
        }) : wx.showModal({
            title: "",
            content: "易方达旗下基金披露的公开季报未显示持有你输入内容的相关权益资产！",
            success: function(o) {
                o.confirm ? console.log("用户点击确定") : console.log("用户点击取消");
            }
        }));
    }
});