var a = getApp();

Page({
    data: {
        fundmanager: "",
        fund_firstcode: [ {
            firstcode: "007548",
            name: "ESG责任投资",
            manager: "郭杰"
        }, {
            firstcode: "510900",
            name: "H股ETF",
            manager: "余海燕,成曦"
        }, {
            firstcode: "110031",
            name: "H股ETF联接",
            manager: "余海燕,成曦"
        }, {
            firstcode: "512090",
            name: "MSCI易基",
            manager: "范冰"
        }, {
            firstcode: "006704",
            name: "MSCI易基联接",
            manager: "范冰"
        }, {
            firstcode: "006319",
            name: "安瑞短债",
            manager: "王晓晨,石大怿"
        }, {
            firstcode: "110027",
            name: "安心回报",
            manager: "张清华"
        }, {
            firstcode: "001182",
            name: "安心回馈",
            manager: "张清华,林森"
        }, {
            firstcode: "001603",
            name: "安盈回报",
            manager: "张清华"
        }, {
            firstcode: "110052",
            name: "安源中短债",
            manager: "李一硕"
        }, {
            firstcode: "006662",
            name: "安悦超短债",
            manager: "刘朝阳,梁莹"
        }, {
            firstcode: "159001",
            name: "保证金",
            manager: "石大怿,梁莹"
        }, {
            firstcode: "161125",
            name: "标普500",
            manager: "范冰,刘树荣"
        }, {
            firstcode: "161128",
            name: "标普科技",
            manager: "范冰"
        }, {
            firstcode: "161127",
            name: "标普生物",
            manager: "范冰"
        }, {
            firstcode: "161126",
            name: "标普医药",
            manager: "范冰"
        }, {
            firstcode: "000647",
            name: "财富快线",
            manager: "石大怿,梁莹,刘朝阳"
        }, {
            firstcode: "110002",
            name: "策略成长",
            manager: "梁裕宁"
        }, {
            firstcode: "112002",
            name: "策略二号",
            manager: "梁裕宁"
        }, {
            firstcode: "000603",
            name: "创新驱动",
            manager: "葛秋石,祁禾"
        }, {
            firstcode: "159915",
            name: "创业板ETF",
            manager: "成曦,刘树荣"
        }, {
            firstcode: "110026",
            name: "创业板ETF联接",
            manager: "成曦,刘树荣"
        }, {
            firstcode: "110037",
            name: "纯债",
            manager: "张雅君"
        }, {
            firstcode: "000111",
            name: "纯债1年",
            manager: "李一硕"
        }, {
            firstcode: "001898",
            name: "大健康",
            manager: "萧楠,杨桢霄"
        }, {
            firstcode: "512070",
            name: "非银ETF",
            manager: "余海燕"
        }, {
            firstcode: "000950",
            name: "非银ETF联接",
            manager: "余海燕"
        }, {
            firstcode: "002969",
            name: "丰和债券",
            manager: "张清华"
        }, {
            firstcode: "000189",
            name: "丰华",
            manager: "张清华,王成"
        }, {
            firstcode: "002602",
            name: "丰惠",
            manager: "胡剑"
        }, {
            firstcode: "005667",
            name: "富财纯债",
            manager: "王晓晨,张雅君"
        }, {
            firstcode: "003214",
            name: "富惠纯债",
            manager: "胡剑"
        }, {
            firstcode: "001076",
            name: "改革红利",
            manager: "郭杰"
        }, {
            firstcode: "005583",
            name: "港股通红利",
            manager: "陈宏初,毕仲圆"
        }, {
            firstcode: "000147",
            name: "高等级债",
            manager: "林森"
        }, {
            firstcode: "009049",
            name: "高端制造",
            manager: "祁禾"
        }, {
            firstcode: "118002",
            name: "高端消费品",
            manager: "张胜记"
        }, {
            firstcode: "002910",
            name: "供给改革",
            manager: "兰传杰,杨宗昌"
        }, {
            firstcode: "001475",
            name: "国防军工",
            manager: "陈皓,何崇恺"
        }, {
            firstcode: "001382",
            name: "国企改革",
            manager: "郭杰"
        }, {
            firstcode: "502006",
            name: "国企改革分级",
            manager: "余海燕"
        }, {
            firstcode: "110015",
            name: "行业领先",
            manager: "冯波"
        }, {
            firstcode: "005439",
            name: "恒安定开",
            manager: "王晓晨"
        }, {
            firstcode: "006112",
            name: "恒惠定开",
            manager: "李一硕"
        }, {
            firstcode: "000265",
            name: "恒久添利",
            manager: "藏海涛"
        }, {
            firstcode: "007104",
            name: "恒利定开",
            manager: "胡剑,纪玲云"
        }, {
            firstcode: "007884",
            name: "恒盛3个月定开",
            manager: "胡剑,纪玲云"
        }, {
            firstcode: "005740",
            name: "恒信定开",
            manager: "李一硕"
        }, {
            firstcode: "007451",
            name: "恒兴3个月定开",
            manager: "王晓晨,张雅君"
        }, {
            firstcode: "005124",
            name: "恒益定开",
            manager: "胡剑,李一硕"
        }, {
            firstcode: "009050",
            name: "恒裕一年定开",
            manager: "纪玲云"
        }, {
            firstcode: "510310",
            name: "沪深300ETF",
            manager: "余海燕"
        }, {
            firstcode: "110020",
            name: "沪深300ETF联接",
            manager: "余海燕"
        }, {
            firstcode: "110030",
            name: "沪深300量化",
            manager: "官泽帆,黄健生"
        }, {
            firstcode: "512010",
            name: "沪深300医药ETF",
            manager: "余海燕"
        }, {
            firstcode: "001344",
            name: "沪深300医药ETF联接",
            manager: "余海燕"
        }, {
            firstcode: "001856",
            name: "环保主题",
            manager: "祁禾"
        }, {
            firstcode: "159934",
            name: "黄金ETF",
            manager: "范冰,余海燕"
        }, {
            firstcode: "000307",
            name: "黄金ETF联接",
            manager: "范冰,余海燕"
        }, {
            firstcode: "161116",
            name: "黄金主题",
            manager: "周宇"
        }, {
            firstcode: "006859",
            name: "汇诚养老2033",
            manager: "汪玲"
        }, {
            firstcode: "006860",
            name: "汇诚养老2038",
            manager: "汪玲"
        }, {
            firstcode: "006292",
            name: "汇诚养老2043",
            manager: "汪玲"
        }, {
            firstcode: "007247",
            name: "汇智稳健养老FOF",
            manager: "杨培鸿,汪玲"
        }, {
            firstcode: "110005",
            name: "积极成长",
            manager: "王超"
        }, {
            firstcode: "110010",
            name: "价值成长",
            manager: "林高榜,武阳"
        }, {
            firstcode: "110009",
            name: "价值精选",
            manager: "葛秋石"
        }, {
            firstcode: "008283",
            name: "金融行业",
            manager: "林高榜"
        }, {
            firstcode: "502003",
            name: "军工分级",
            manager: "余海燕"
        }, {
            firstcode: "110012",
            name: "科汇",
            manager: "杨嘉文"
        }, {
            firstcode: "007346",
            name: "科技创新",
            manager: "刘武,蔡荣成"
        }, {
            firstcode: "006533",
            name: "科融",
            manager: "陈皓"
        }, {
            firstcode: "003293",
            name: "科瑞",
            manager: "杨嘉文"
        }, {
            firstcode: "161132",
            name: "科顺",
            manager: "萧楠"
        }, {
            firstcode: "110013",
            name: "科翔",
            manager: "陈皓"
        }, {
            firstcode: "110029",
            name: "科讯",
            manager: "陈皓,刘健维"
        }, {
            firstcode: "005827",
            name: "蓝筹精选",
            manager: "张坤"
        }, {
            firstcode: "002216",
            name: "量化策略",
            manager: "官泽帆,黄健生"
        }, {
            firstcode: "000789",
            name: "龙宝",
            manager: "石大怿,梁莹"
        }, {
            firstcode: "161130",
            name: "纳指100LOF",
            manager: "范冰"
        }, {
            firstcode: "009292",
            name: "年年恒春一年定开",
            manager: "李一硕"
        }, {
            firstcode: "007997",
            name: "年年恒秋纯债",
            manager: "李一硕"
        }, {
            firstcode: "007525",
            name: "年年恒夏一年定开",
            manager: "李一硕"
        }, {
            firstcode: "008284",
            name: "全球医药",
            manager: "杨桢霄"
        }, {
            firstcode: "110001",
            name: "平稳增长",
            manager: "陈皓"
        }, {
            firstcode: "513000",
            name: "日兴资管日经225ETF",
            manager: "范冰,余海燕"
        }, {
            firstcode: "001802",
            name: "瑞财",
            manager: "纪玲云"
        }, {
            firstcode: "003961",
            name: "瑞程",
            manager: "林森"
        }, {
            firstcode: "009215",
            name: "瑞川",
            manager: "杨康"
        }, {
            firstcode: "001745",
            name: "瑞富",
            manager: "胡剑"
        }, {
            firstcode: "001562",
            name: "瑞和",
            manager: "韩阅川"
        }, {
            firstcode: "001832",
            name: "瑞恒",
            manager: "萧楠,王元春"
        }, {
            firstcode: "003882",
            name: "瑞弘",
            manager: "林森"
        }, {
            firstcode: "001433",
            name: "瑞景",
            manager: "韩阅川"
        }, {
            firstcode: "001747",
            name: "瑞祺",
            manager: "韩阅川"
        }, {
            firstcode: "003839",
            name: "瑞通",
            manager: "林森"
        }, {
            firstcode: "001835",
            name: "瑞祥",
            manager: "韩阅川"
        }, {
            firstcode: "001437",
            name: "瑞享",
            manager: "武阳"
        }, {
            firstcode: "001441",
            name: "瑞信",
            manager: "韩阅川"
        }, {
            firstcode: "001817",
            name: "瑞兴",
            manager: "韩阅川"
        }, {
            firstcode: "001443",
            name: "瑞选",
            manager: "韩阅川"
        }, {
            firstcode: "001806",
            name: "瑞智",
            manager: "韩阅川"
        }, {
            firstcode: "510100",
            name: "上证50ETF",
            manager: "余海燕,成曦"
        }, {
            firstcode: "007379",
            name: "上证50ETF联接",
            manager: "余海燕,成曦"
        }, {
            firstcode: "502048",
            name: "上证50分级",
            manager: "余海燕"
        }, {
            firstcode: "110003",
            name: "上证50指数",
            manager: "张胜记"
        }, {
            firstcode: "110021",
            name: "上证中盘ETF联接",
            manager: "刘树荣"
        }, {
            firstcode: "159901",
            name: "深100ETF",
            manager: "成曦,刘树荣"
        }, {
            firstcode: "110019",
            name: "深100ETF联接",
            manager: "成曦,刘树荣"
        }, {
            firstcode: "161122",
            name: "生物分级",
            manager: "刘树荣"
        }, {
            firstcode: "110035",
            name: "双债增强",
            manager: "王晓晨"
        }, {
            firstcode: "161115",
            name: "岁丰添利",
            manager: "胡剑"
        }, {
            firstcode: "000829",
            name: "天天发",
            manager: "石大怿"
        }, {
            firstcode: "000009",
            name: "天天理财",
            manager: "石大怿,刘朝阳"
        }, {
            firstcode: "000704",
            name: "天天增利",
            manager: "石大怿,梁莹"
        }, {
            firstcode: "000205",
            name: "投资级债",
            manager: "王晓晨"
        }, {
            firstcode: "110007",
            name: "稳健收益",
            manager: "胡剑"
        }, {
            firstcode: "001857",
            name: "现代服务业",
            manager: "萧楠,王元春"
        }, {
            firstcode: "000620",
            name: "现金增利",
            manager: "石大怿,梁莹"
        }, {
            firstcode: "161124",
            name: "香港小盘",
            manager: "刘树荣"
        }, {
            firstcode: "513090",
            name: "香港证券",
            manager: "范冰,成曦"
        }, {
            firstcode: "110022",
            name: "消费行业",
            manager: "萧楠"
        }, {
            firstcode: "009265",
            name: "消费精选",
            manager: "萧楠"
        }, {
            firstcode: "001184",
            name: "新常态",
            manager: "赵锴,孙松"
        }, {
            firstcode: "001018",
            name: "新经济",
            manager: "陈皓"
        }, {
            firstcode: "001249",
            name: "新利",
            manager: "韩阅川"
        }, {
            firstcode: "001216",
            name: "新收益",
            manager: "张清华"
        }, {
            firstcode: "001373",
            name: "新丝路",
            manager: "张坤,祁禾"
        }, {
            firstcode: "001342",
            name: "新享",
            manager: "韩阅川"
        }, {
            firstcode: "001285",
            name: "新鑫",
            manager: "韩阅川"
        }, {
            firstcode: "000404",
            name: "新兴成长",
            manager: "刘武"
        }, {
            firstcode: "001314",
            name: "新益",
            manager: "韩阅川"
        }, {
            firstcode: "005955",
            name: "鑫转添利",
            manager: "韩阅川"
        }, {
            firstcode: "005876",
            name: "鑫转增利",
            manager: "杨康"
        }, {
            firstcode: "006013",
            name: "鑫转招利",
            manager: "韩阅川,杨康"
        }, {
            firstcode: "001513",
            name: "信息产业",
            manager: "郑希"
        }, {
            firstcode: "000032",
            name: "信用债",
            manager: "胡剑,纪玲云"
        }, {
            firstcode: "118001",
            name: "亚洲精选",
            manager: "张坤"
        }, {
            firstcode: "008286",
            name: "研究精选",
            manager: "冯波"
        }, {
            firstcode: "110023",
            name: "医疗行业",
            manager: "杨桢霄"
        }, {
            firstcode: "005437",
            name: "易百量化",
            manager: "官泽帆"
        }, {
            firstcode: "110006",
            name: "易方达货币",
            manager: "石大怿"
        }, {
            firstcode: "161117",
            name: "易基永旭",
            manager: "李一硕"
        }, {
            firstcode: "161119",
            name: "易基综债",
            manager: "王晓晨"
        }, {
            firstcode: "000359",
            name: "易理财",
            manager: "石大怿,刘朝阳"
        }, {
            firstcode: "161121",
            name: "银行分级",
            manager: "刘树荣"
        }, {
            firstcode: "007896",
            name: "优选多资产三个月",
            manager: "杨培鸿,张浩然"
        }, {
            firstcode: "000171",
            name: "裕丰回报",
            manager: "张清华,张雅君"
        }, {
            firstcode: "008556",
            name: "裕富",
            manager: "张雅君"
        }, {
            firstcode: "000436",
            name: "裕惠回报",
            manager: "胡剑"
        }, {
            firstcode: "002600",
            name: "裕景添利",
            manager: "林森"
        }, {
            firstcode: "001136",
            name: "裕如",
            manager: "李一硕"
        }, {
            firstcode: "002351",
            name: "裕祥回报",
            manager: "张清华,林森"
        }, {
            firstcode: "003133",
            name: "裕鑫",
            manager: "韩阅川"
        }, {
            firstcode: "161129",
            name: "原油基金",
            manager: "范冰,成曦"
        }, {
            firstcode: "110050",
            name: "月月利",
            manager: "石大怿,梁莹"
        }, {
            firstcode: "001010",
            name: "增金宝",
            manager: "梁莹"
        }, {
            firstcode: "110017",
            name: "增强回报",
            manager: "王晓晨,张雅君"
        }, {
            firstcode: "161131",
            name: "战略配售",
            manager: "胡剑,纪玲云,付浩"
        }, {
            firstcode: "000833",
            name: "掌柜季季盈",
            manager: "石大怿,梁莹"
        }, {
            firstcode: "159803",
            name: "浙江新动能ETF",
            manager: "杨俊"
        }, {
            firstcode: "007813",
            name: "浙江新动能ETF联接",
            manager: "杨俊"
        }, {
            firstcode: "502010",
            name: "证券公司分级",
            manager: "余海燕"
        }, {
            firstcode: "007360",
            name: "中短期美元债",
            manager: "祁广东,周怡"
        }, {
            firstcode: "513050",
            name: "中概互联",
            manager: "余海燕,范冰"
        }, {
            firstcode: "006327",
            name: "中概互联ETF联接",
            manager: "余海燕,范冰"
        }, {
            firstcode: "510130",
            name: "中盘ETF",
            manager: "刘树荣"
        }, {
            firstcode: "005875",
            name: "中盘成长",
            manager: "冯波"
        }, {
            firstcode: "161118",
            name: "中小板指数",
            manager: "刘树荣"
        }, {
            firstcode: "110011",
            name: "中小盘",
            manager: "张坤"
        }, {
            firstcode: "007169",
            name: "中债1-3年国开行",
            manager: "王晓晨"
        }, {
            firstcode: "007364",
            name: "中债1-3年政策性金融债",
            manager: "王晓晨"
        }, {
            firstcode: "007171",
            name: "中债3-5年国开行",
            manager: "王晓晨"
        }, {
            firstcode: "001512",
            name: "中债3-5年国债",
            manager: "胡剑"
        }, {
            firstcode: "007366",
            name: "中债3-5年政策性金融债",
            manager: "王晓晨"
        }, {
            firstcode: "003358",
            name: "中债7-10年国开",
            manager: "胡剑"
        }, {
            firstcode: "510580",
            name: "中证500ETF",
            manager: "余海燕"
        }, {
            firstcode: "007028",
            name: "中证500ETF联接",
            manager: "余海燕"
        }, {
            firstcode: "515810",
            name: "中证800ETF",
            manager: "林伟斌,刘树荣"
        }, {
            firstcode: "007856",
            name: "中证800ETF联接",
            manager: "林伟斌,刘树荣"
        }, {
            firstcode: "515110",
            name: "中证国企一带一路ETF",
            manager: "杨俊,刘树荣"
        }, {
            firstcode: "007788",
            name: "中证国企一带一路ETF联接",
            manager: "杨俊,刘树荣"
        }, {
            firstcode: "515180",
            name: "中证红利ETF",
            manager: "林伟斌"
        }, {
            firstcode: "512560",
            name: "中证军工",
            manager: "余海燕"
        }, {
            firstcode: "159807",
            name: "中证科技50ETF",
            manager: "张湛"
        }, {
            firstcode: "512570",
            name: "中证证券",
            manager: "余海燕"
        }, {
            firstcode: "161123",
            name: "重组分级",
            manager: "刘树荣"
        }, {
            firstcode: "110025",
            name: "资源行业",
            manager: "兰传杰"
        } ],
        fundlist: []
    },
    back: function(a) {
        wx.switchTab({
            url: "../index/index"
        });
    },
    onLoad: function(a) {},
    onReady: function() {},
    onShow: function() {
        this.setData({
            fundmanager: a.globalData.fundmanager
        });
        for (var e = this.data.fundmanager, n = [], r = 0; r < this.data.fund_firstcode.length; r++) this.data.fund_firstcode[r].manager.match(RegExp(e)) && n.push({
            arrfirstcode: this.data.fund_firstcode[r].firstcode,
            arrname: this.data.fund_firstcode[r].name
        });
        this.setData({
            fundlist: n
        }), console.log("fundlist:", fundlist), console.log("fundmanager:", e);
    },
    getcode: function(e) {
        console.log(e.currentTarget.id), this.setData({
            code: e.currentTarget.id
        }), a.globalData.code = e.currentTarget.id, console.log(a.globalData.code);
    },
    gogogo: function(e) {
        a.globalData.address = "fundmanager/fundmanager", wx.redirectTo({
            url: "../onefund/onefund",
            success: function() {
                console.log("seccess go");
            },
            fail: function() {
                console.log("fail go");
            }
        });
    },
    onHide: function() {},
    onUnload: function() {},
    onPullDownRefresh: function() {},
    onReachBottom: function() {},
    onShareAppMessage: function(a) {
        return "button" === a.from && console.log(a.target), {
            title: "看净值·读季报·查基金",
            path: "/pages/fundvalue/fundvalue",
            imageUrl: "/pages/image/fengmian.jpg",
            success: function(a) {
                console.log("转发成功:");
            },
            fail: function(a) {
                console.log("转发失败:");
            }
        };
    }
});