Object.defineProperty(exports, "__esModule", {
    value: !0
});

var PAGE_MAP = {
    "pages/classlist/classlist": "班级列表",
    "pages/authorize/index": "授权页",
    "pages/getCity/index": "获取城市",
    "pages/searchgrade/searchgrade": "选择年级",
    "pages/loginRelevant/cityclass": "完善信息页",
    "pages/openCity/openCity": "选择孩子所在城市页",
    "pages/loginRelevant/inputphone": "手机号快捷登录",
    "pages/loginRelevant/bindphone": "手机号绑定",
    "pages/loginRelevant/numpassword": "账号密码登录",
    "pages/loginRelevant/verification": "输入验证码",
    "pages/personcenter/personinfo": "我的",
    "pages/internal/qrcode": "小程序生成二维码",
    "pages/classlist/pointclasslist": "精品课",
    "pages/classlist/activity": "选课报班",
    "pages/classlist/classdetail/online": "在线课程详情页",
    "pages/classlist/classdetail/double": "双师课程详情页",
    "pages/classlist/classdetail/offline": "面授课程详情页",
    "pages/personcenter/info": "个人信息页",
    "pages/personcenter/addressmanage": "收获地址页",
    "pages/personcenter/addPage": "添加收货地址",
    "pages/courselist/coursepay": "购课单",
    "pages/courselist/downloadapp": "下载app",
    "pages/wait/waitcoursebuy": "待付款",
    "pages/alreadypay/alreadypaylist": "已付款",
    "pages/courselist/orderdetail": "订单详情页",
    "pages/alreadypay/userProtocol": "用户协议",
    "pages/courselist/paydone": "支付成功页",
    "pages/courselist/coupon": "我的优惠券页",
    "pages/conmmonwebview/index": "轮播跳转h5页面",
    "pages/banner/banner": "轮播跳转h5【旧版】页面",
    "pages/teacherDetails/index": "老师详情页",
    "pages/unionEnroll/index": "联报活动首页"
}, SCENE_VALUE = {
    1001: "小程序历史列表",
    1005: "搜索",
    1006: "搜索",
    1042: "搜索",
    1053: "搜索",
    1054: "搜索",
    1027: "搜索",
    1011: "小程序码",
    1012: "小程序码",
    1013: "小程序码",
    1047: "小程序码",
    1048: "小程序码",
    1049: "小程序码",
    1007: "单聊会话",
    1008: "群聊会话",
    1020: "公众号主页",
    1014: "小程序模板消息",
    1026: "附近的小程序",
    1035: "公众号菜单",
    1036: "APP分享",
    1037: "别的小程序",
    1043: "公众号模板消息",
    1058: "公众号文章",
    1091: "公众号文章",
    1089: "小程序任务栏",
    default: "其他"
};

exports.PAGE_MAP = PAGE_MAP, exports.SCENE_VALUE = SCENE_VALUE;