var e = getApp();

Page({
    data: {
        fundstyle: e.globalData.fundstyle,
        stockfund: [ {
            code: "007548",
            firstcode: "007548",
            name: "ESG责任投资",
            allname: "易方达ESG责任投资股票型发起式证券投资基金",
            type: "股票型",
            subtype: "标准股票型"
        }, {
            code: "008283",
            firstcode: "008283",
            name: "金融行业",
            allname: "易方达金融行业股票型发起式证券投资基金",
            type: "股票型",
            subtype: "行业主题股票型"
        }, {
            code: "110022",
            firstcode: "110022",
            name: "消费行业",
            allname: "易方达消费行业股票型证券投资基金",
            type: "股票型",
            subtype: "行业主题股票型"
        }, {
            code: "009265",
            firstcode: "009265",
            name: "消费精选",
            allname: "易方达消费精选股票型证券投资基金",
            type: "股票型",
            subtype: "行业主题股票型"
        }, {
            code: "008286",
            firstcode: "008286",
            name: "研究精选",
            allname: "易方达研究精选股票型证券投资基金",
            type: "股票型",
            subtype: "标准股票型"
        } ],
        mixedfund: [ {
            code: "001182",
            firstcode: "001182",
            name: "安心回馈",
            allname: "易方达安心回馈混合型证券投资基金",
            type: "混合型",
            subtype: "偏债型"
        }, {
            code: "001603",
            firstcode: "001603",
            name: "安盈回报",
            allname: "易方达安盈回报混合型证券投资基金",
            type: "混合型",
            subtype: "偏债型"
        }, {
            code: "110002",
            firstcode: "110002",
            name: "策略成长",
            allname: "易方达策略成长证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "112002",
            firstcode: "112002",
            name: "策略二号",
            allname: "易方达策略成长二号混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "000603",
            firstcode: "000603",
            name: "创新驱动",
            allname: "易方达创新驱动灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001898",
            firstcode: "001898",
            name: "大健康",
            allname: "易方达大健康主题灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "002602",
            firstcode: "002602",
            name: "丰惠",
            allname: "易方达丰惠混合型证券投资基金",
            type: "混合型",
            subtype: "偏债型"
        }, {
            code: "001076",
            firstcode: "001076",
            name: "改革红利",
            allname: "易方达改革红利混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "005583",
            firstcode: "005583",
            name: "港股通红利",
            allname: "易方达港股通红利灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "009049",
            firstcode: "009049",
            name: "高端制造",
            allname: "易方达高端制造混合型发起式证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "002910",
            firstcode: "002910",
            name: "供给改革",
            allname: "易方达供给改革灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001475",
            firstcode: "001475",
            name: "国防军工",
            allname: "易方达国防军工混合型证券投资基金",
            type: "混合型",
            subtype: "行业主题偏股型"
        }, {
            code: "001382",
            firstcode: "001382",
            name: "国企改革",
            allname: "易方达国企改革混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "110015",
            firstcode: "110015",
            name: "行业领先",
            allname: "易方达行业领先企业混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "007884",
            firstcode: "007884",
            name: "恒盛3个月定开",
            allname: "易方达恒盛3个月定期开放混合型发起式证券投资基金",
            type: "混合型",
            subtype: "定期开放式偏债型"
        }, {
            code: "001856",
            firstcode: "001856",
            name: "环保主题",
            allname: "易方达环保主题灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "110005",
            firstcode: "110005",
            name: "积极成长",
            allname: "易方达积极成长证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "110010",
            firstcode: "110010",
            name: "价值成长",
            allname: "易方达价值成长混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "110009",
            firstcode: "110009",
            name: "价值精选",
            allname: "易方达价值精选混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "110012",
            firstcode: "110012",
            name: "科汇",
            allname: "易方达科汇灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "007346",
            firstcode: "007346",
            name: "科技创新",
            allname: "易方达科技创新混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "006533",
            firstcode: "006533",
            name: "科融",
            allname: "易方达科融混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "003293",
            firstcode: "003293",
            name: "科瑞",
            allname: "易方达科瑞灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "161132",
            firstcode: "161132",
            name: "科顺",
            allname: "易方达科顺定期开放灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "定期开放灵活配置型"
        }, {
            code: "110013",
            firstcode: "110013",
            name: "科翔",
            allname: "易方达科翔混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "110029",
            firstcode: "110029",
            name: "科讯",
            allname: "易方达科讯混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "005827",
            firstcode: "005827",
            name: "蓝筹精选",
            allname: "易方达蓝筹精选混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "002216",
            firstcode: "002216",
            name: "量化策略",
            allname: "易方达量化策略精选灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "110001",
            firstcode: "110001",
            name: "平稳增长",
            allname: "易方达平稳增长证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "001802",
            firstcode: "001802",
            name: "瑞财",
            allname: "易方达瑞财灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "003961",
            firstcode: "003961",
            name: "瑞程",
            allname: "易方达瑞程灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "009215",
            firstcode: "009215",
            name: "瑞川",
            allname: "易方达瑞川灵活配置混合型发起式证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001745",
            firstcode: "001745",
            name: "瑞富",
            allname: "易方达瑞富灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001562",
            firstcode: "001562",
            name: "瑞和",
            allname: "易方达瑞和灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001832",
            firstcode: "001832",
            name: "瑞恒",
            allname: "易方达瑞恒灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "003882",
            firstcode: "003882",
            name: "瑞弘",
            allname: "易方达瑞弘灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001433",
            firstcode: "001433",
            name: "瑞景",
            allname: "易方达瑞景灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001747",
            firstcode: "001747",
            name: "瑞祺",
            allname: "易方达瑞祺灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "003839",
            firstcode: "003839",
            name: "瑞通",
            allname: "易方达瑞通灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001835",
            firstcode: "001835",
            name: "瑞祥",
            allname: "易方达瑞祥灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001437",
            firstcode: "001437",
            name: "瑞享",
            allname: "易方达瑞享灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001441",
            firstcode: "001441",
            name: "瑞信",
            allname: "易方达瑞信灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001817",
            firstcode: "001817",
            name: "瑞兴",
            allname: "易方达瑞兴灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001443",
            firstcode: "001443",
            name: "瑞选",
            allname: "易方达瑞选灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001806",
            firstcode: "001806",
            name: "瑞智",
            allname: "易方达瑞智灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001857",
            firstcode: "001857",
            name: "现代服务业",
            allname: "易方达现代服务业灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001184",
            firstcode: "001184",
            name: "新常态",
            allname: "易方达新常态灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001018",
            firstcode: "001018",
            name: "新经济",
            allname: "易方达新经济灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001249",
            firstcode: "001249",
            name: "新利",
            allname: "易方达新利灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001216",
            firstcode: "001216",
            name: "新收益",
            allname: "易方达新收益灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001373",
            firstcode: "001373",
            name: "新丝路",
            allname: "易方达新丝路灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001342",
            firstcode: "001342",
            name: "新享",
            allname: "易方达新享灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001285",
            firstcode: "001285",
            name: "新鑫",
            allname: "易方达新鑫灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "000404",
            firstcode: "000404",
            name: "新兴成长",
            allname: "易方达新兴成长灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "001314",
            firstcode: "001314",
            name: "新益",
            allname: "易方达新益灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "005955",
            firstcode: "005955",
            name: "鑫转添利",
            allname: "易方达鑫转添利混合型证券投资基金",
            type: "混合型",
            subtype: "偏债型"
        }, {
            code: "005876",
            firstcode: "005876",
            name: "鑫转增利",
            allname: "易方达鑫转增利混合型证券投资基金",
            type: "混合型",
            subtype: "偏债型"
        }, {
            code: "006013",
            firstcode: "006013",
            name: "鑫转招利",
            allname: "易方达鑫转招利混合型证券投资基金",
            type: "混合型",
            subtype: "偏债型"
        }, {
            code: "001513",
            firstcode: "001513",
            name: "信息产业",
            allname: "易方达信息产业混合型证券投资基金",
            type: "混合型",
            subtype: "行业主题偏股型"
        }, {
            code: "110023",
            firstcode: "110023",
            name: "医疗行业",
            allname: "易方达医疗保健行业混合型证券投资基金",
            type: "混合型",
            subtype: "行业主题偏股型"
        }, {
            code: "005437",
            firstcode: "005437",
            name: "易百量化",
            allname: "易方达易百智能量化策略灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "000436",
            firstcode: "000436",
            name: "裕惠回报",
            allname: "易方达裕惠回报定期开放式混合型发起式证券投资基金",
            type: "混合型",
            subtype: "偏债型"
        }, {
            code: "001136",
            firstcode: "001136",
            name: "裕如",
            allname: "易方达裕如灵活配置混合型证券投资基金",
            type: "混合型",
            subtype: "灵活配置型"
        }, {
            code: "161131",
            firstcode: "161131",
            name: "战略配售",
            allname: "易方达3年封闭运作战略配售灵活配置混合型证券投资基金(LOF)",
            type: "混合型",
            subtype: "封闭式灵活配置型"
        }, {
            code: "005875",
            firstcode: "005875",
            name: "中盘成长",
            allname: "易方达中盘成长混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "110011",
            firstcode: "110011",
            name: "中小盘",
            allname: "易方达中小盘混合型证券投资基金",
            type: "混合型",
            subtype: "偏股型"
        }, {
            code: "110025",
            firstcode: "110025",
            name: "资源行业",
            allname: "易方达资源行业混合型证券投资基金",
            type: "混合型",
            subtype: "行业主题偏股型"
        } ],
        indexfund: [ {
            code: "512090",
            firstcode: "512090",
            name: "MSCI易基",
            allname: "易方达MSCI中国A股国际通交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "006704",
            firstcode: "006704",
            name: "MSCI易基联接",
            allname: "易方达MSCI中国A股国际通交易型开放式指数证券投资基金发起式联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "159915",
            firstcode: "159915",
            name: "创业板ETF",
            allname: "易方达创业板交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "110026",
            firstcode: "110026",
            name: "创业板ETF联接",
            allname: "易方达创业板交易型开放式指数证券投资基金联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "512070",
            firstcode: "512070",
            name: "非银ETF",
            allname: "易方达沪深300非银行金融交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "000950",
            firstcode: "000950",
            name: "非银ETF联接",
            allname: "易方达沪深300非银行金融交易型开放式指数证券投资基金联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "502006",
            firstcode: "502006",
            name: "国企改革分级",
            allname: "易方达国企改革指数分级证券投资基金",
            type: "指数型",
            subtype: "标准指数股票型"
        }, {
            code: "510310",
            firstcode: "510310",
            name: "沪深300ETF",
            allname: "易方达沪深300交易型开放式指数发起式证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "110020",
            firstcode: "110020",
            name: "沪深300ETF联接",
            allname: "易方达沪深300交易型开放式指数发起式证券投资基金联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "110030",
            firstcode: "110030",
            name: "沪深300量化",
            allname: "易方达沪深300量化增强证券投资基金",
            type: "指数型",
            subtype: "增强指数股票型"
        }, {
            code: "512010",
            firstcode: "512010",
            name: "沪深300医药ETF",
            allname: "易方达沪深300医药卫生交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "001344",
            firstcode: "001344",
            name: "沪深300医药ETF联接",
            allname: "易方达沪深300医药卫生交易型开放式指数证券投资基金联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "502003",
            firstcode: "502003",
            name: "军工分级",
            allname: "易方达军工指数分级证券投资基金",
            type: "指数型",
            subtype: "标准指数股票型"
        }, {
            code: "510100",
            firstcode: "510100",
            name: "上证50ETF",
            allname: "易方达上证50交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "007379",
            firstcode: "007379",
            name: "上证50ETF联接",
            allname: "易方达上证50交易型开放式指数证券投资基金发起式联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "502048",
            firstcode: "502048",
            name: "上证50分级",
            allname: "易方达上证50指数分级证券投资基金",
            type: "指数型",
            subtype: "标准指数股票型"
        }, {
            code: "110003",
            firstcode: "110003",
            name: "上证50指数",
            allname: "易方达50指数证券投资基金",
            type: "指数型",
            subtype: "增强指数股票型"
        }, {
            code: "110021",
            firstcode: "110021",
            name: "上证中盘ETF联接",
            allname: "易方达上证中盘交易型开放式指数证券投资基金联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "159901",
            firstcode: "159901",
            name: "深100ETF",
            allname: "易方达深证100交易型开放式指数基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "110019",
            firstcode: "110019",
            name: "深100ETF联接",
            allname: "易方达深证100交易型开放式指数证券投资基金联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "161122",
            firstcode: "161122",
            name: "生物分级",
            allname: "易方达生物科技指数分级证券投资基金",
            type: "指数型",
            subtype: "标准指数股票型"
        }, {
            code: "513090",
            firstcode: "513090",
            name: "香港证券",
            allname: "易方达中证香港证券投资主题交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "161121",
            firstcode: "161121",
            name: "银行分级",
            allname: "易方达银行指数分级证券投资基金",
            type: "指数型",
            subtype: "标准指数股票型"
        }, {
            code: "159803",
            firstcode: "159803",
            name: "浙江新动能ETF",
            allname: "易方达中证浙江新动能交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "007813",
            firstcode: "007813",
            name: "浙江新动能ETF联接",
            allname: "易方达中证浙江新动能交易型开放式指数证券投资基金联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "502010",
            firstcode: "502010",
            name: "证券公司分级",
            allname: "易方达证券公司指数分级证券投资基金",
            type: "指数型",
            subtype: "标准指数股票型"
        }, {
            code: "510130",
            firstcode: "510130",
            name: "中盘ETF",
            allname: "易方达上证中盘交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "161118",
            firstcode: "161118",
            name: "中小板指数",
            allname: "易方达中小板指数证券投资基金（LOF）",
            type: "指数型",
            subtype: "标准指数股票型"
        }, {
            code: "510580",
            firstcode: "510580",
            name: "中证500ETF",
            allname: "易方达中证500交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "007028",
            firstcode: "007028",
            name: "中证500ETF联接",
            allname: "易方达中证500交易型开放式指数证券投资基金发起式联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "515810",
            firstcode: "515810",
            name: "中证800ETF",
            allname: "易方达中证800交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "007856",
            firstcode: "007856",
            name: "中证800ETF联接",
            allname: "易方达中证800交易型开放式指数证券投资基金发起式联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "515110",
            firstcode: "515110",
            name: "中证国企一带一路ETF",
            allname: "易方达中证国企一带一路交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "007788",
            firstcode: "007788",
            name: "中证国企一带一路ETF联接",
            allname: "易方达中证国企一带一路交易型开放式指数证券投资基金联接基金",
            type: "指数型",
            subtype: "股票ETF联接"
        }, {
            code: "515180",
            firstcode: "515180",
            name: "中证红利ETF",
            allname: "易方达中证红利交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "512560",
            firstcode: "512560",
            name: "中证军工",
            allname: "易方达中证军工交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "159807",
            firstcode: "159807",
            name: "中证科技50ETF",
            allname: "易方达中证科技50交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "512570",
            firstcode: "512570",
            name: "中证证券",
            allname: "易方达中证全指证券公司交易型开放式指数证券投资基金",
            type: "指数型",
            subtype: "股票ETF"
        }, {
            code: "161123",
            firstcode: "161123",
            name: "重组分级",
            allname: "易方达并购重组指数分级证券投资基金",
            type: "指数型",
            subtype: "标准指数股票型"
        } ],
        bondfund: [ {
            code: "006319",
            firstcode: "006319",
            name: "安瑞短债",
            allname: "易方达安瑞短债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "110027",
            firstcode: "110027",
            name: "安心回报",
            allname: "易方达安心回报债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(二级)"
        }, {
            code: "110052",
            firstcode: "110052",
            name: "安源中短债",
            allname: "易方达安源中短债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "006662",
            firstcode: "006662",
            name: "安悦超短债",
            allname: "易方达安悦超短债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "110037",
            firstcode: "110037",
            name: "纯债",
            allname: "易方达纯债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "000111",
            firstcode: "000111",
            name: "纯债1年",
            allname: "易方达纯债1年定期开放债券型证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "002969",
            firstcode: "002969",
            name: "丰和债券",
            allname: "易方达丰和债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(二级)"
        }, {
            code: "000189",
            firstcode: "000189",
            name: "丰华",
            allname: "易方达丰华债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(二级)"
        }, {
            code: "005667",
            firstcode: "005667",
            name: "富财纯债",
            allname: "易方达富财纯债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "003214",
            firstcode: "003214",
            name: "富惠纯债",
            allname: "易方达富惠纯债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "000147",
            firstcode: "000147",
            name: "高等级债",
            allname: "易方达高等级信用债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "005439",
            firstcode: "005439",
            name: "恒安定开",
            allname: "易方达恒安定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "006112",
            firstcode: "006112",
            name: "恒惠定开",
            allname: "易方达恒惠定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "000265",
            firstcode: "000265",
            name: "恒久添利",
            allname: "易方达恒久添利1年定期开放债券型证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "007104",
            firstcode: "007104",
            name: "恒利定开",
            allname: "易方达恒利3个月定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "005740",
            firstcode: "005740",
            name: "恒信定开",
            allname: "易方达恒信定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "007451",
            firstcode: "007451",
            name: "恒兴3个月定开",
            allname: "易方达恒兴3个月定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放式纯债型"
        }, {
            code: "005124",
            firstcode: "005124",
            name: "恒益定开",
            allname: "易方达恒益定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "009050",
            firstcode: "009050",
            name: "恒裕一年定开",
            allname: "易方达恒裕一年定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "009292",
            firstcode: "009292",
            name: "年年恒春一年定开",
            allname: "易方达年年恒春纯债一年定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "007997",
            firstcode: "007997",
            name: "年年恒秋纯债",
            allname: "易方达年年恒秋纯债一年定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "007525",
            firstcode: "007525",
            name: "年年恒夏一年定开",
            allname: "易方达年年恒夏纯债一年定期开放债券型发起式证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "110035",
            firstcode: "110035",
            name: "双债增强",
            allname: "易方达双债增强债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(可投转债)"
        }, {
            code: "161115",
            firstcode: "161115",
            name: "岁丰添利",
            allname: "易方达岁丰添利债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(可投转债)"
        }, {
            code: "000205",
            firstcode: "000205",
            name: "投资级债",
            allname: "易方达投资级信用债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "110007",
            firstcode: "110007",
            name: "稳健收益",
            allname: "易方达稳健收益债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(二级)"
        }, {
            code: "000032",
            firstcode: "000032",
            name: "信用债",
            allname: "易方达信用债债券型证券投资基金",
            type: "债券型",
            subtype: "纯债债券型"
        }, {
            code: "161117",
            firstcode: "161117",
            name: "易基永旭",
            allname: "易方达永旭添利定期开放债券型证券投资基金",
            type: "债券型",
            subtype: "定期开放纯债债券型"
        }, {
            code: "161119",
            firstcode: "161119",
            name: "易基综债",
            allname: "易方达中债新综合债券指数发起式证券投资基金(LOF)",
            type: "债券型",
            subtype: "指数债券型"
        }, {
            code: "000171",
            firstcode: "000171",
            name: "裕丰回报",
            allname: "易方达裕丰回报债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(二级)"
        }, {
            code: "008556",
            firstcode: "008556",
            name: "裕富",
            allname: "易方达裕富债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(二级)"
        }, {
            code: "002600",
            firstcode: "002600",
            name: "裕景添利",
            allname: "易方达裕景添利6个月定期开放债券型证券投资基金",
            type: "债券型",
            subtype: "定期开放普通债券型(可投转债)"
        }, {
            code: "002351",
            firstcode: "002351",
            name: "裕祥回报",
            allname: "易方达裕祥回报债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(二级)"
        }, {
            code: "003133",
            firstcode: "003133",
            name: "裕鑫",
            allname: "易方达裕鑫债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(二级)"
        }, {
            code: "110050",
            firstcode: "110050",
            name: "月月利",
            allname: "易方达月月利理财债券型证券投资基金",
            type: "债券型",
            subtype: "短期理财债券型"
        }, {
            code: "110017",
            firstcode: "110017",
            name: "增强回报",
            allname: "易方达增强回报债券型证券投资基金",
            type: "债券型",
            subtype: "普通债券型(可投转债)"
        }, {
            code: "000833",
            firstcode: "000833",
            name: "掌柜季季盈",
            allname: "易方达掌柜季季盈理财债券型证券投资基金",
            type: "债券型",
            subtype: "短期理财债券型"
        }, {
            code: "007169",
            firstcode: "007169",
            name: "中债1-3年国开行",
            allname: "易方达中债1-3年国开行债券指数证券投资基金",
            type: "债券型",
            subtype: "指数债券型"
        }, {
            code: "007364",
            firstcode: "007364",
            name: "中债1-3年政策性金融债",
            allname: "易方达中债1-3年政策性金融债指数证券投资基金",
            type: "债券型",
            subtype: "指数债券型"
        }, {
            code: "007171",
            firstcode: "007171",
            name: "中债3-5年国开行",
            allname: "易方达中债3-5年国开行债券指数证券投资基金",
            type: "债券型",
            subtype: "指数债券型"
        }, {
            code: "001512",
            firstcode: "001512",
            name: "中债3-5年国债",
            allname: "易方达中债3-5年期国债指数证券投资基金",
            type: "债券型",
            subtype: "指数债券型"
        }, {
            code: "007366",
            firstcode: "007366",
            name: "中债3-5年政策性金融债",
            allname: "易方达中债3-5年政策性金融债指数证券投资基金",
            type: "债券型",
            subtype: "指数债券型"
        }, {
            code: "003358",
            firstcode: "003358",
            name: "中债7-10年国开",
            allname: "易方达中债7-10年期国开行债券指数证券投资基金",
            type: "债券型",
            subtype: "指数债券型"
        } ],
        monetaryfund: [ {
            code: "159001",
            firstcode: "159001",
            name: "保证金",
            allname: "易方达保证金收益货币市场基金",
            type: "货币型",
            subtype: "交易型货币市场"
        }, {
            code: "000647",
            firstcode: "000647",
            name: "财富快线",
            allname: "易方达财富快线货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        }, {
            code: "000789",
            firstcode: "000789",
            name: "龙宝",
            allname: "易方达龙宝货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        }, {
            code: "000829",
            firstcode: "000829",
            name: "天天发",
            allname: "易方达天天发货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        }, {
            code: "000009",
            firstcode: "000009",
            name: "天天理财",
            allname: "易方达天天理财货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        }, {
            code: "000704",
            firstcode: "000704",
            name: "天天增利",
            allname: "易方达天天增利货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        }, {
            code: "000620",
            firstcode: "000620",
            name: "现金增利",
            allname: "易方达现金增利货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        }, {
            code: "110006",
            firstcode: "110006",
            name: "易方达货币",
            allname: "易方达货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        }, {
            code: "000359",
            firstcode: "000359",
            name: "易理财",
            allname: "易方达易理财货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        }, {
            code: "001010",
            firstcode: "001010",
            name: "增金宝",
            allname: "易方达增金宝货币市场基金",
            type: "货币型",
            subtype: "普通货币市场"
        } ],
        commodityfund: [ {
            code: "159934",
            firstcode: "159934",
            name: "黄金ETF",
            allname: "易方达黄金交易型开放式证券投资基金",
            type: "商品型",
            subtype: "黄金基金"
        }, {
            code: "000307",
            firstcode: "000307",
            name: "黄金ETF联接",
            allname: "易方达黄金交易型开放式证券投资基金联接基金",
            type: "商品型",
            subtype: "黄金基金"
        }, {
            code: "161116",
            firstcode: "161116",
            name: "黄金主题",
            allname: "易方达黄金主题证券投资基金(LOF)",
            type: "商品型",
            subtype: "黄金基金"
        }, {
            code: "161129",
            firstcode: "161129",
            name: "原油基金",
            allname: "易方达原油证券投资基金(QDII)",
            type: "商品型",
            subtype: "原油基金"
        } ],
        qdiifund: [ {
            code: "510900",
            firstcode: "510900",
            name: "H股ETF",
            allname: "易方达恒生中国企业交易型开放式指数证券投资基金",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "110031",
            firstcode: "110031",
            name: "H股ETF联接",
            allname: "易方达恒生中国企业交易型开放式指数证券投资基金联接基金",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "161125",
            firstcode: "161125",
            name: "标普500",
            allname: "易方达标普500指数证券投资基金(LOF)",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "161128",
            firstcode: "161128",
            name: "标普科技",
            allname: "易方达标普信息科技指数证券投资基金(LOF)",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "161127",
            firstcode: "161127",
            name: "标普生物",
            allname: "易方达标普生物科技指数证券投资基金(LOF)",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "161126",
            firstcode: "161126",
            name: "标普医药",
            allname: "易方达标普医疗保健指数证券投资基金(LOF)",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "118002",
            firstcode: "118002",
            name: "高端消费品",
            allname: "易方达标普全球高端消费品指数增强型证券投资基金",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "161130",
            firstcode: "161130",
            name: "纳指100LOF",
            allname: "易方达纳斯达克100指数证券投资基金(LOF)",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "008284",
            firstcode: "008284",
            name: "全球医药",
            allname: "易方达全球医药行业混合型发起式证券投资基金",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "513000",
            firstcode: "513000",
            name: "日兴资管日经225ETF",
            allname: "易方达日兴资管日经225交易型开放式指数证券投资基金(QDII)",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "161124",
            firstcode: "161124",
            name: "香港小盘",
            allname: "易方达香港恒生综合小型股指数证券投资基金(LOF)",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "118001",
            firstcode: "118001",
            name: "亚洲精选",
            allname: "易方达亚洲精选股票型证券投资基金",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "007360",
            firstcode: "007360",
            name: "中短期美元债",
            allname: "易方达中短期美元债债券型证券投资基金",
            type: "QDII",
            subtype: "债券型"
        }, {
            code: "513050",
            firstcode: "513050",
            name: "中概互联",
            allname: "易方达中证海外中国互联网50交易型开放式指数证券投资基金",
            type: "QDII",
            subtype: "股票型"
        }, {
            code: "006327",
            firstcode: "006327",
            name: "中概互联ETF联接",
            allname: "易方达中证海外中国互联网50交易型开放式指数证券投资基金联接基金",
            type: "QDII",
            subtype: "股票型"
        } ],
        foffund: [ {
            code: "006859",
            firstcode: "006859",
            name: "汇诚养老2033",
            allname: "易方达汇诚养老目标日期2033三年持有期混合型发起式基金中基金(FOF)",
            type: "FOF",
            subtype: "养老目标日期FOF"
        }, {
            code: "006860",
            firstcode: "006860",
            name: "汇诚养老2038",
            allname: "易方达汇诚养老目标日期2038三年持有期混合型发起式基金中基金(FOF)",
            type: "FOF",
            subtype: "养老目标日期FOF"
        }, {
            code: "006292",
            firstcode: "006292",
            name: "汇诚养老2043",
            allname: "易方达汇诚养老目标日期2043三年持有期混合型基金中基金(FOF)",
            type: "FOF",
            subtype: "养老目标日期FOF"
        }, {
            code: "007247",
            firstcode: "007247",
            name: "汇智稳健养老FOF",
            allname: "易方达汇智稳健养老目标一年持有期混合型基金中基金(FOF)",
            type: "FOF",
            subtype: "养老目标风险FOF"
        }, {
            code: "007896",
            firstcode: "007896",
            name: "优选多资产三个月",
            allname: "易方达优选多资产三个月持有期混合型基金中基金(FOF)",
            type: "FOF",
            subtype: "混合型FOF"
        } ],
        stockfundstyle: [ {
            style: "标准股票型"
        }, {
            style: "行业主题股票型"
        } ],
        mixedfundstyle: [ {
            style: "偏股型"
        }, {
            style: "行业主题偏股型"
        }, {
            style: "灵活配置型"
        }, {
            style: "定期开放灵活配置型"
        }, {
            style: "定期开放式偏债型"
        }, {
            style: "封闭式灵活配置型"
        }, {
            style: "偏债型"
        } ],
        indexfundstyle: [ {
            style: "标准指数股票型"
        }, {
            style: "增强指数股票型"
        }, {
            style: "股票ETF"
        }, {
            style: "股票ETF联接"
        } ],
        bondfundstyle: [ {
            style: "纯债债券型"
        }, {
            style: "定期开放纯债债券型"
        }, {
            style: "定期开放普通债券型(可投转债)"
        }, {
            style: "定期开放式纯债型"
        }, {
            style: "短期理财债券型"
        }, {
            style: "普通债券型(二级)"
        }, {
            style: "普通债券型(可投转债)"
        }, {
            style: "指数债券型"
        } ],
        monetaryfundstyle: [ {
            style: "普通货币市场"
        }, {
            style: "交易型货币市场"
        } ],
        commodityfundstyle: [ {
            style: "黄金基金"
        }, {
            style: "原油基金"
        } ],
        qdiifundstyle: [ {
            style: "股票型"
        }, {
            style: "债券型"
        } ],
        foffundstyle: [ {
            style: "混合型FOF"
        }, {
            style: "养老目标风险FOF"
        }, {
            style: "养老目标日期FOF"
        } ]
    },
    back: function(e) {
        wx.switchTab({
            url: "../index/index"
        });
    },
    onLoad: function() {},
    getcode: function(t) {
        console.log(t.currentTarget.id), this.setData({
            code: t.currentTarget.id
        }), e.globalData.code = t.currentTarget.id, console.log(e.globalData.code);
    },
    gogogo: function(t) {
        e.globalData.address = "fundlist/fundlist", wx.redirectTo({
            url: "../onefund/onefund",
            success: function() {
                console.log("seccess go");
            },
            fail: function() {
                console.log("fail go");
            }
        });
    },
    onShow: function() {
        this.setData({
            fundstyle: e.globalData.fundstyle
        });
    },
    onShareAppMessage: function(e) {
        return "button" === e.from && console.log(e.target), {
            title: "看净值·读季报·查基金",
            path: "/pages/fundvalue/fundvalue",
            imageUrl: "/pages/image/fengmian.jpg",
            success: function(e) {
                console.log("转发成功:");
            },
            fail: function(e) {
                console.log("转发失败:");
            }
        };
    }
});